run:
  timeout: 5m
  issues-exit-code: 0
  tests: false
  build-tags:
    - linux
    - libsqlite3
    - sqlite_fts5
linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Other linters
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    # - contextcheck
    - dupl
    - durationcheck
    - gofmt
    - gosec
    - makezero
    - noctx
    - prealloc
    - unparam
    - sqlclosecheck
    - rowserrcheck
linters-settings:
  gosimple:
    checks: ["all"]
  staticcheck:
    checks: ["all"]
  dupl:
    threshold: 125